// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package graphql

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/Khan/genqlient/graphql"
)

// AddCertificateAddCertificateAddCertificatePayload includes the requested fields of the GraphQL type AddCertificatePayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of AddCertificate
type AddCertificateAddCertificateAddCertificatePayload struct {
	Certificate AddCertificateAddCertificateAddCertificatePayloadCertificateAppCertificate `json:"certificate"`
}

// GetCertificate returns AddCertificateAddCertificateAddCertificatePayload.Certificate, and is useful for accessing the field via an interface.
func (v *AddCertificateAddCertificateAddCertificatePayload) GetCertificate() AddCertificateAddCertificateAddCertificatePayloadCertificateAppCertificate {
	return v.Certificate
}

// AddCertificateAddCertificateAddCertificatePayloadCertificateAppCertificate includes the requested fields of the GraphQL type AppCertificate.
type AddCertificateAddCertificateAddCertificatePayloadCertificateAppCertificate struct {
	Id                        string `json:"id"`
	DnsValidationInstructions string `json:"dnsValidationInstructions"`
	DnsValidationHostname     string `json:"dnsValidationHostname"`
	DnsValidationTarget       string `json:"dnsValidationTarget"`
	Hostname                  string `json:"hostname"`
	Check                     bool   `json:"check"`
}

// GetId returns AddCertificateAddCertificateAddCertificatePayloadCertificateAppCertificate.Id, and is useful for accessing the field via an interface.
func (v *AddCertificateAddCertificateAddCertificatePayloadCertificateAppCertificate) GetId() string {
	return v.Id
}

// GetDnsValidationInstructions returns AddCertificateAddCertificateAddCertificatePayloadCertificateAppCertificate.DnsValidationInstructions, and is useful for accessing the field via an interface.
func (v *AddCertificateAddCertificateAddCertificatePayloadCertificateAppCertificate) GetDnsValidationInstructions() string {
	return v.DnsValidationInstructions
}

// GetDnsValidationHostname returns AddCertificateAddCertificateAddCertificatePayloadCertificateAppCertificate.DnsValidationHostname, and is useful for accessing the field via an interface.
func (v *AddCertificateAddCertificateAddCertificatePayloadCertificateAppCertificate) GetDnsValidationHostname() string {
	return v.DnsValidationHostname
}

// GetDnsValidationTarget returns AddCertificateAddCertificateAddCertificatePayloadCertificateAppCertificate.DnsValidationTarget, and is useful for accessing the field via an interface.
func (v *AddCertificateAddCertificateAddCertificatePayloadCertificateAppCertificate) GetDnsValidationTarget() string {
	return v.DnsValidationTarget
}

// GetHostname returns AddCertificateAddCertificateAddCertificatePayloadCertificateAppCertificate.Hostname, and is useful for accessing the field via an interface.
func (v *AddCertificateAddCertificateAddCertificatePayloadCertificateAppCertificate) GetHostname() string {
	return v.Hostname
}

// GetCheck returns AddCertificateAddCertificateAddCertificatePayloadCertificateAppCertificate.Check, and is useful for accessing the field via an interface.
func (v *AddCertificateAddCertificateAddCertificatePayloadCertificateAppCertificate) GetCheck() bool {
	return v.Check
}

// AddCertificateResponse is returned by AddCertificate on success.
type AddCertificateResponse struct {
	AddCertificate AddCertificateAddCertificateAddCertificatePayload `json:"addCertificate"`
}

// GetAddCertificate returns AddCertificateResponse.AddCertificate, and is useful for accessing the field via an interface.
func (v *AddCertificateResponse) GetAddCertificate() AddCertificateAddCertificateAddCertificatePayload {
	return v.AddCertificate
}

// Autogenerated input type of AddWireGuardPeer
type AddWireGuardPeerInput struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationId string `json:"clientMutationId"`
	// The node ID of the organization
	OrganizationId string `json:"organizationId"`
	// The region in which to deploy the peer
	Region string `json:"region"`
	// The name with which to refer to the peer
	Name string `json:"name"`
	// The 25519 public key for the peer
	Pubkey string `json:"pubkey"`
	// Network ID to attach wireguard peer to
	Network string `json:"network"`
	// Add via NATS transaction (deprecated - nats is always used)
	Nats bool `json:"nats"`
}

// GetClientMutationId returns AddWireGuardPeerInput.ClientMutationId, and is useful for accessing the field via an interface.
func (v *AddWireGuardPeerInput) GetClientMutationId() string { return v.ClientMutationId }

// GetOrganizationId returns AddWireGuardPeerInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *AddWireGuardPeerInput) GetOrganizationId() string { return v.OrganizationId }

// GetRegion returns AddWireGuardPeerInput.Region, and is useful for accessing the field via an interface.
func (v *AddWireGuardPeerInput) GetRegion() string { return v.Region }

// GetName returns AddWireGuardPeerInput.Name, and is useful for accessing the field via an interface.
func (v *AddWireGuardPeerInput) GetName() string { return v.Name }

// GetPubkey returns AddWireGuardPeerInput.Pubkey, and is useful for accessing the field via an interface.
func (v *AddWireGuardPeerInput) GetPubkey() string { return v.Pubkey }

// GetNetwork returns AddWireGuardPeerInput.Network, and is useful for accessing the field via an interface.
func (v *AddWireGuardPeerInput) GetNetwork() string { return v.Network }

// GetNats returns AddWireGuardPeerInput.Nats, and is useful for accessing the field via an interface.
func (v *AddWireGuardPeerInput) GetNats() bool { return v.Nats }

// AddWireguardPeerAddWireGuardPeerAddWireGuardPeerPayload includes the requested fields of the GraphQL type AddWireGuardPeerPayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of AddWireGuardPeer
type AddWireguardPeerAddWireGuardPeerAddWireGuardPeerPayload struct {
	Network    string `json:"network"`
	Endpointip string `json:"endpointip"`
	Peerip     string `json:"peerip"`
	Pubkey     string `json:"pubkey"`
}

// GetNetwork returns AddWireguardPeerAddWireGuardPeerAddWireGuardPeerPayload.Network, and is useful for accessing the field via an interface.
func (v *AddWireguardPeerAddWireGuardPeerAddWireGuardPeerPayload) GetNetwork() string {
	return v.Network
}

// GetEndpointip returns AddWireguardPeerAddWireGuardPeerAddWireGuardPeerPayload.Endpointip, and is useful for accessing the field via an interface.
func (v *AddWireguardPeerAddWireGuardPeerAddWireGuardPeerPayload) GetEndpointip() string {
	return v.Endpointip
}

// GetPeerip returns AddWireguardPeerAddWireGuardPeerAddWireGuardPeerPayload.Peerip, and is useful for accessing the field via an interface.
func (v *AddWireguardPeerAddWireGuardPeerAddWireGuardPeerPayload) GetPeerip() string { return v.Peerip }

// GetPubkey returns AddWireguardPeerAddWireGuardPeerAddWireGuardPeerPayload.Pubkey, and is useful for accessing the field via an interface.
func (v *AddWireguardPeerAddWireGuardPeerAddWireGuardPeerPayload) GetPubkey() string { return v.Pubkey }

// AddWireguardPeerResponse is returned by AddWireguardPeer on success.
type AddWireguardPeerResponse struct {
	AddWireGuardPeer AddWireguardPeerAddWireGuardPeerAddWireGuardPeerPayload `json:"addWireGuardPeer"`
}

// GetAddWireGuardPeer returns AddWireguardPeerResponse.AddWireGuardPeer, and is useful for accessing the field via an interface.
func (v *AddWireguardPeerResponse) GetAddWireGuardPeer() AddWireguardPeerAddWireGuardPeerAddWireGuardPeerPayload {
	return v.AddWireGuardPeer
}

// AllocateIpAddressAllocateIpAddressAllocateIPAddressPayload includes the requested fields of the GraphQL type AllocateIPAddressPayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of AllocateIPAddress
type AllocateIpAddressAllocateIpAddressAllocateIPAddressPayload struct {
	IpAddress AllocateIpAddressAllocateIpAddressAllocateIPAddressPayloadIpAddressIPAddress `json:"ipAddress"`
}

// GetIpAddress returns AllocateIpAddressAllocateIpAddressAllocateIPAddressPayload.IpAddress, and is useful for accessing the field via an interface.
func (v *AllocateIpAddressAllocateIpAddressAllocateIPAddressPayload) GetIpAddress() AllocateIpAddressAllocateIpAddressAllocateIPAddressPayloadIpAddressIPAddress {
	return v.IpAddress
}

// AllocateIpAddressAllocateIpAddressAllocateIPAddressPayloadIpAddressIPAddress includes the requested fields of the GraphQL type IPAddress.
type AllocateIpAddressAllocateIpAddressAllocateIPAddressPayloadIpAddressIPAddress struct {
	Id      string        `json:"id"`
	Type    IPAddressType `json:"type"`
	Address string        `json:"address"`
	Region  string        `json:"region"`
}

// GetId returns AllocateIpAddressAllocateIpAddressAllocateIPAddressPayloadIpAddressIPAddress.Id, and is useful for accessing the field via an interface.
func (v *AllocateIpAddressAllocateIpAddressAllocateIPAddressPayloadIpAddressIPAddress) GetId() string {
	return v.Id
}

// GetType returns AllocateIpAddressAllocateIpAddressAllocateIPAddressPayloadIpAddressIPAddress.Type, and is useful for accessing the field via an interface.
func (v *AllocateIpAddressAllocateIpAddressAllocateIPAddressPayloadIpAddressIPAddress) GetType() IPAddressType {
	return v.Type
}

// GetAddress returns AllocateIpAddressAllocateIpAddressAllocateIPAddressPayloadIpAddressIPAddress.Address, and is useful for accessing the field via an interface.
func (v *AllocateIpAddressAllocateIpAddressAllocateIPAddressPayloadIpAddressIPAddress) GetAddress() string {
	return v.Address
}

// GetRegion returns AllocateIpAddressAllocateIpAddressAllocateIPAddressPayloadIpAddressIPAddress.Region, and is useful for accessing the field via an interface.
func (v *AllocateIpAddressAllocateIpAddressAllocateIPAddressPayloadIpAddressIPAddress) GetRegion() string {
	return v.Region
}

// AllocateIpAddressResponse is returned by AllocateIpAddress on success.
type AllocateIpAddressResponse struct {
	AllocateIpAddress AllocateIpAddressAllocateIpAddressAllocateIPAddressPayload `json:"allocateIpAddress"`
}

// GetAllocateIpAddress returns AllocateIpAddressResponse.AllocateIpAddress, and is useful for accessing the field via an interface.
func (v *AllocateIpAddressResponse) GetAllocateIpAddress() AllocateIpAddressAllocateIpAddressAllocateIPAddressPayload {
	return v.AllocateIpAddress
}

// Region autoscaling configuration
type AutoscaleRegionConfigInput struct {
	// The region code to configure
	Code string `json:"code"`
	// The weight
	Weight int `json:"weight"`
	// Minimum number of VMs to run in this region
	MinCount int `json:"minCount"`
	// Reset the configuration for this region
	Reset bool `json:"reset"`
}

// GetCode returns AutoscaleRegionConfigInput.Code, and is useful for accessing the field via an interface.
func (v *AutoscaleRegionConfigInput) GetCode() string { return v.Code }

// GetWeight returns AutoscaleRegionConfigInput.Weight, and is useful for accessing the field via an interface.
func (v *AutoscaleRegionConfigInput) GetWeight() int { return v.Weight }

// GetMinCount returns AutoscaleRegionConfigInput.MinCount, and is useful for accessing the field via an interface.
func (v *AutoscaleRegionConfigInput) GetMinCount() int { return v.MinCount }

// GetReset returns AutoscaleRegionConfigInput.Reset, and is useful for accessing the field via an interface.
func (v *AutoscaleRegionConfigInput) GetReset() bool { return v.Reset }

// CreateAppMutationCreateAppCreateAppPayload includes the requested fields of the GraphQL type CreateAppPayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of CreateApp
type CreateAppMutationCreateAppCreateAppPayload struct {
	App CreateAppMutationCreateAppCreateAppPayloadApp `json:"app"`
}

// GetApp returns CreateAppMutationCreateAppCreateAppPayload.App, and is useful for accessing the field via an interface.
func (v *CreateAppMutationCreateAppCreateAppPayload) GetApp() CreateAppMutationCreateAppCreateAppPayloadApp {
	return v.App
}

// CreateAppMutationCreateAppCreateAppPayloadApp includes the requested fields of the GraphQL type App.
type CreateAppMutationCreateAppCreateAppPayloadApp struct {
	// The unique application name
	Name string `json:"name"`
	// Application status
	Status string `json:"status"`
	// Organization that owns this app
	Organization CreateAppMutationCreateAppCreateAppPayloadAppOrganization `json:"organization"`
}

// GetName returns CreateAppMutationCreateAppCreateAppPayloadApp.Name, and is useful for accessing the field via an interface.
func (v *CreateAppMutationCreateAppCreateAppPayloadApp) GetName() string { return v.Name }

// GetStatus returns CreateAppMutationCreateAppCreateAppPayloadApp.Status, and is useful for accessing the field via an interface.
func (v *CreateAppMutationCreateAppCreateAppPayloadApp) GetStatus() string { return v.Status }

// GetOrganization returns CreateAppMutationCreateAppCreateAppPayloadApp.Organization, and is useful for accessing the field via an interface.
func (v *CreateAppMutationCreateAppCreateAppPayloadApp) GetOrganization() CreateAppMutationCreateAppCreateAppPayloadAppOrganization {
	return v.Organization
}

// CreateAppMutationCreateAppCreateAppPayloadAppOrganization includes the requested fields of the GraphQL type Organization.
type CreateAppMutationCreateAppCreateAppPayloadAppOrganization struct {
	Id string `json:"id"`
	// Unique organization slug
	Slug string `json:"slug"`
}

// GetId returns CreateAppMutationCreateAppCreateAppPayloadAppOrganization.Id, and is useful for accessing the field via an interface.
func (v *CreateAppMutationCreateAppCreateAppPayloadAppOrganization) GetId() string { return v.Id }

// GetSlug returns CreateAppMutationCreateAppCreateAppPayloadAppOrganization.Slug, and is useful for accessing the field via an interface.
func (v *CreateAppMutationCreateAppCreateAppPayloadAppOrganization) GetSlug() string { return v.Slug }

// CreateAppMutationResponse is returned by CreateAppMutation on success.
type CreateAppMutationResponse struct {
	CreateApp CreateAppMutationCreateAppCreateAppPayload `json:"createApp"`
}

// GetCreateApp returns CreateAppMutationResponse.CreateApp, and is useful for accessing the field via an interface.
func (v *CreateAppMutationResponse) GetCreateApp() CreateAppMutationCreateAppCreateAppPayload {
	return v.CreateApp
}

// CreatePostgresClusterCreatePostgresClusterCreatePostgresClusterPayload includes the requested fields of the GraphQL type CreatePostgresClusterPayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of CreatePostgresCluster
type CreatePostgresClusterCreatePostgresClusterCreatePostgresClusterPayload struct {
	App      CreatePostgresClusterCreatePostgresClusterCreatePostgresClusterPayloadApp `json:"app"`
	Username string                                                                    `json:"username"`
	Password string                                                                    `json:"password"`
}

// GetApp returns CreatePostgresClusterCreatePostgresClusterCreatePostgresClusterPayload.App, and is useful for accessing the field via an interface.
func (v *CreatePostgresClusterCreatePostgresClusterCreatePostgresClusterPayload) GetApp() CreatePostgresClusterCreatePostgresClusterCreatePostgresClusterPayloadApp {
	return v.App
}

// GetUsername returns CreatePostgresClusterCreatePostgresClusterCreatePostgresClusterPayload.Username, and is useful for accessing the field via an interface.
func (v *CreatePostgresClusterCreatePostgresClusterCreatePostgresClusterPayload) GetUsername() string {
	return v.Username
}

// GetPassword returns CreatePostgresClusterCreatePostgresClusterCreatePostgresClusterPayload.Password, and is useful for accessing the field via an interface.
func (v *CreatePostgresClusterCreatePostgresClusterCreatePostgresClusterPayload) GetPassword() string {
	return v.Password
}

// CreatePostgresClusterCreatePostgresClusterCreatePostgresClusterPayloadApp includes the requested fields of the GraphQL type App.
type CreatePostgresClusterCreatePostgresClusterCreatePostgresClusterPayloadApp struct {
	// The unique application name
	Name string `json:"name"`
}

// GetName returns CreatePostgresClusterCreatePostgresClusterCreatePostgresClusterPayloadApp.Name, and is useful for accessing the field via an interface.
func (v *CreatePostgresClusterCreatePostgresClusterCreatePostgresClusterPayloadApp) GetName() string {
	return v.Name
}

// CreatePostgresClusterResponse is returned by CreatePostgresCluster on success.
type CreatePostgresClusterResponse struct {
	CreatePostgresCluster CreatePostgresClusterCreatePostgresClusterCreatePostgresClusterPayload `json:"createPostgresCluster"`
}

// GetCreatePostgresCluster returns CreatePostgresClusterResponse.CreatePostgresCluster, and is useful for accessing the field via an interface.
func (v *CreatePostgresClusterResponse) GetCreatePostgresCluster() CreatePostgresClusterCreatePostgresClusterCreatePostgresClusterPayload {
	return v.CreatePostgresCluster
}

// CreateVolumeCreateVolumeCreateVolumePayload includes the requested fields of the GraphQL type CreateVolumePayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of CreateVolume
type CreateVolumeCreateVolumeCreateVolumePayload struct {
	Volume CreateVolumeCreateVolumeCreateVolumePayloadVolume `json:"volume"`
}

// GetVolume returns CreateVolumeCreateVolumeCreateVolumePayload.Volume, and is useful for accessing the field via an interface.
func (v *CreateVolumeCreateVolumeCreateVolumePayload) GetVolume() CreateVolumeCreateVolumeCreateVolumePayloadVolume {
	return v.Volume
}

// CreateVolumeCreateVolumeCreateVolumePayloadVolume includes the requested fields of the GraphQL type Volume.
type CreateVolumeCreateVolumeCreateVolumePayloadVolume struct {
	Name       string `json:"name"`
	Region     string `json:"region"`
	Id         string `json:"id"`
	InternalId string `json:"internalId"`
	SizeGb     int    `json:"sizeGb"`
}

// GetName returns CreateVolumeCreateVolumeCreateVolumePayloadVolume.Name, and is useful for accessing the field via an interface.
func (v *CreateVolumeCreateVolumeCreateVolumePayloadVolume) GetName() string { return v.Name }

// GetRegion returns CreateVolumeCreateVolumeCreateVolumePayloadVolume.Region, and is useful for accessing the field via an interface.
func (v *CreateVolumeCreateVolumeCreateVolumePayloadVolume) GetRegion() string { return v.Region }

// GetId returns CreateVolumeCreateVolumeCreateVolumePayloadVolume.Id, and is useful for accessing the field via an interface.
func (v *CreateVolumeCreateVolumeCreateVolumePayloadVolume) GetId() string { return v.Id }

// GetInternalId returns CreateVolumeCreateVolumeCreateVolumePayloadVolume.InternalId, and is useful for accessing the field via an interface.
func (v *CreateVolumeCreateVolumeCreateVolumePayloadVolume) GetInternalId() string {
	return v.InternalId
}

// GetSizeGb returns CreateVolumeCreateVolumeCreateVolumePayloadVolume.SizeGb, and is useful for accessing the field via an interface.
func (v *CreateVolumeCreateVolumeCreateVolumePayloadVolume) GetSizeGb() int { return v.SizeGb }

// CreateVolumeResponse is returned by CreateVolume on success.
type CreateVolumeResponse struct {
	CreateVolume CreateVolumeCreateVolumeCreateVolumePayload `json:"createVolume"`
}

// GetCreateVolume returns CreateVolumeResponse.CreateVolume, and is useful for accessing the field via an interface.
func (v *CreateVolumeResponse) GetCreateVolume() CreateVolumeCreateVolumeCreateVolumePayload {
	return v.CreateVolume
}

// DeleteAppMutationDeleteAppDeleteAppPayload includes the requested fields of the GraphQL type DeleteAppPayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of DeleteApp
type DeleteAppMutationDeleteAppDeleteAppPayload struct {
	// The organization that owned the deleted app
	Organization DeleteAppMutationDeleteAppDeleteAppPayloadOrganization `json:"organization"`
}

// GetOrganization returns DeleteAppMutationDeleteAppDeleteAppPayload.Organization, and is useful for accessing the field via an interface.
func (v *DeleteAppMutationDeleteAppDeleteAppPayload) GetOrganization() DeleteAppMutationDeleteAppDeleteAppPayloadOrganization {
	return v.Organization
}

// DeleteAppMutationDeleteAppDeleteAppPayloadOrganization includes the requested fields of the GraphQL type Organization.
type DeleteAppMutationDeleteAppDeleteAppPayloadOrganization struct {
	// Organization name
	Name string `json:"name"`
}

// GetName returns DeleteAppMutationDeleteAppDeleteAppPayloadOrganization.Name, and is useful for accessing the field via an interface.
func (v *DeleteAppMutationDeleteAppDeleteAppPayloadOrganization) GetName() string { return v.Name }

// DeleteAppMutationResponse is returned by DeleteAppMutation on success.
type DeleteAppMutationResponse struct {
	// Delete an app
	DeleteApp DeleteAppMutationDeleteAppDeleteAppPayload `json:"deleteApp"`
}

// GetDeleteApp returns DeleteAppMutationResponse.DeleteApp, and is useful for accessing the field via an interface.
func (v *DeleteAppMutationResponse) GetDeleteApp() DeleteAppMutationDeleteAppDeleteAppPayload {
	return v.DeleteApp
}

// DeleteCertificateDeleteCertificateDeleteCertificatePayload includes the requested fields of the GraphQL type DeleteCertificatePayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of DeleteCertificate
type DeleteCertificateDeleteCertificateDeleteCertificatePayload struct {
	App         DeleteCertificateDeleteCertificateDeleteCertificatePayloadApp                       `json:"app"`
	Certificate DeleteCertificateDeleteCertificateDeleteCertificatePayloadCertificateAppCertificate `json:"certificate"`
}

// GetApp returns DeleteCertificateDeleteCertificateDeleteCertificatePayload.App, and is useful for accessing the field via an interface.
func (v *DeleteCertificateDeleteCertificateDeleteCertificatePayload) GetApp() DeleteCertificateDeleteCertificateDeleteCertificatePayloadApp {
	return v.App
}

// GetCertificate returns DeleteCertificateDeleteCertificateDeleteCertificatePayload.Certificate, and is useful for accessing the field via an interface.
func (v *DeleteCertificateDeleteCertificateDeleteCertificatePayload) GetCertificate() DeleteCertificateDeleteCertificateDeleteCertificatePayloadCertificateAppCertificate {
	return v.Certificate
}

// DeleteCertificateDeleteCertificateDeleteCertificatePayloadApp includes the requested fields of the GraphQL type App.
type DeleteCertificateDeleteCertificateDeleteCertificatePayloadApp struct {
	// The unique application name
	Name string `json:"name"`
}

// GetName returns DeleteCertificateDeleteCertificateDeleteCertificatePayloadApp.Name, and is useful for accessing the field via an interface.
func (v *DeleteCertificateDeleteCertificateDeleteCertificatePayloadApp) GetName() string {
	return v.Name
}

// DeleteCertificateDeleteCertificateDeleteCertificatePayloadCertificateAppCertificate includes the requested fields of the GraphQL type AppCertificate.
type DeleteCertificateDeleteCertificateDeleteCertificatePayloadCertificateAppCertificate struct {
	Hostname string `json:"hostname"`
	Id       string `json:"id"`
}

// GetHostname returns DeleteCertificateDeleteCertificateDeleteCertificatePayloadCertificateAppCertificate.Hostname, and is useful for accessing the field via an interface.
func (v *DeleteCertificateDeleteCertificateDeleteCertificatePayloadCertificateAppCertificate) GetHostname() string {
	return v.Hostname
}

// GetId returns DeleteCertificateDeleteCertificateDeleteCertificatePayloadCertificateAppCertificate.Id, and is useful for accessing the field via an interface.
func (v *DeleteCertificateDeleteCertificateDeleteCertificatePayloadCertificateAppCertificate) GetId() string {
	return v.Id
}

// DeleteCertificateResponse is returned by DeleteCertificate on success.
type DeleteCertificateResponse struct {
	DeleteCertificate DeleteCertificateDeleteCertificateDeleteCertificatePayload `json:"deleteCertificate"`
}

// GetDeleteCertificate returns DeleteCertificateResponse.DeleteCertificate, and is useful for accessing the field via an interface.
func (v *DeleteCertificateResponse) GetDeleteCertificate() DeleteCertificateDeleteCertificateDeleteCertificatePayload {
	return v.DeleteCertificate
}

// DeleteVolumeDeleteVolumeDeleteVolumePayload includes the requested fields of the GraphQL type DeleteVolumePayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of DeleteVolume
type DeleteVolumeDeleteVolumeDeleteVolumePayload struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationId string `json:"clientMutationId"`
}

// GetClientMutationId returns DeleteVolumeDeleteVolumeDeleteVolumePayload.ClientMutationId, and is useful for accessing the field via an interface.
func (v *DeleteVolumeDeleteVolumeDeleteVolumePayload) GetClientMutationId() string {
	return v.ClientMutationId
}

// DeleteVolumeResponse is returned by DeleteVolume on success.
type DeleteVolumeResponse struct {
	DeleteVolume DeleteVolumeDeleteVolumeDeleteVolumePayload `json:"deleteVolume"`
}

// GetDeleteVolume returns DeleteVolumeResponse.DeleteVolume, and is useful for accessing the field via an interface.
func (v *DeleteVolumeResponse) GetDeleteVolume() DeleteVolumeDeleteVolumeDeleteVolumePayload {
	return v.DeleteVolume
}

// GetCertificateApp includes the requested fields of the GraphQL type App.
type GetCertificateApp struct {
	// Find a certificate by hostname
	Certificate GetCertificateAppCertificate `json:"certificate"`
}

// GetCertificate returns GetCertificateApp.Certificate, and is useful for accessing the field via an interface.
func (v *GetCertificateApp) GetCertificate() GetCertificateAppCertificate { return v.Certificate }

// GetCertificateAppCertificate includes the requested fields of the GraphQL type AppCertificate.
type GetCertificateAppCertificate struct {
	Id                        string `json:"id"`
	DnsValidationInstructions string `json:"dnsValidationInstructions"`
	DnsValidationHostname     string `json:"dnsValidationHostname"`
	DnsValidationTarget       string `json:"dnsValidationTarget"`
	Hostname                  string `json:"hostname"`
	Check                     bool   `json:"check"`
}

// GetId returns GetCertificateAppCertificate.Id, and is useful for accessing the field via an interface.
func (v *GetCertificateAppCertificate) GetId() string { return v.Id }

// GetDnsValidationInstructions returns GetCertificateAppCertificate.DnsValidationInstructions, and is useful for accessing the field via an interface.
func (v *GetCertificateAppCertificate) GetDnsValidationInstructions() string {
	return v.DnsValidationInstructions
}

// GetDnsValidationHostname returns GetCertificateAppCertificate.DnsValidationHostname, and is useful for accessing the field via an interface.
func (v *GetCertificateAppCertificate) GetDnsValidationHostname() string {
	return v.DnsValidationHostname
}

// GetDnsValidationTarget returns GetCertificateAppCertificate.DnsValidationTarget, and is useful for accessing the field via an interface.
func (v *GetCertificateAppCertificate) GetDnsValidationTarget() string { return v.DnsValidationTarget }

// GetHostname returns GetCertificateAppCertificate.Hostname, and is useful for accessing the field via an interface.
func (v *GetCertificateAppCertificate) GetHostname() string { return v.Hostname }

// GetCheck returns GetCertificateAppCertificate.Check, and is useful for accessing the field via an interface.
func (v *GetCertificateAppCertificate) GetCheck() bool { return v.Check }

// GetCertificateResponse is returned by GetCertificate on success.
type GetCertificateResponse struct {
	// Find an app by name
	App GetCertificateApp `json:"app"`
}

// GetApp returns GetCertificateResponse.App, and is useful for accessing the field via an interface.
func (v *GetCertificateResponse) GetApp() GetCertificateApp { return v.App }

// GetFullAppApp includes the requested fields of the GraphQL type App.
type GetFullAppApp struct {
	// The unique application name
	Name    string `json:"name"`
	Network string `json:"network"`
	// Organization that owns this app
	Organization GetFullAppAppOrganization                 `json:"organization"`
	Autoscaling  GetFullAppAppAutoscalingAutoscalingConfig `json:"autoscaling"`
	AppUrl       string                                    `json:"appUrl"`
	// Autogenerated hostname for this application
	Hostname string `json:"hostname"`
	// Unique application ID
	Id string `json:"id"`
	// Application status
	Status   string `json:"status"`
	Deployed bool   `json:"deployed"`
	// The latest release of this applicaion
	CurrentRelease GetFullAppAppCurrentRelease                   `json:"currentRelease"`
	Config         GetFullAppAppConfig                           `json:"config"`
	HealthChecks   GetFullAppAppHealthChecksCheckStateConnection `json:"healthChecks"`
	IpAddresses    GetFullAppAppIpAddressesIPAddressConnection   `json:"ipAddresses"`
	Role           GetFullAppAppRole                             `json:"-"`
}

// GetName returns GetFullAppApp.Name, and is useful for accessing the field via an interface.
func (v *GetFullAppApp) GetName() string { return v.Name }

// GetNetwork returns GetFullAppApp.Network, and is useful for accessing the field via an interface.
func (v *GetFullAppApp) GetNetwork() string { return v.Network }

// GetOrganization returns GetFullAppApp.Organization, and is useful for accessing the field via an interface.
func (v *GetFullAppApp) GetOrganization() GetFullAppAppOrganization { return v.Organization }

// GetAutoscaling returns GetFullAppApp.Autoscaling, and is useful for accessing the field via an interface.
func (v *GetFullAppApp) GetAutoscaling() GetFullAppAppAutoscalingAutoscalingConfig {
	return v.Autoscaling
}

// GetAppUrl returns GetFullAppApp.AppUrl, and is useful for accessing the field via an interface.
func (v *GetFullAppApp) GetAppUrl() string { return v.AppUrl }

// GetHostname returns GetFullAppApp.Hostname, and is useful for accessing the field via an interface.
func (v *GetFullAppApp) GetHostname() string { return v.Hostname }

// GetId returns GetFullAppApp.Id, and is useful for accessing the field via an interface.
func (v *GetFullAppApp) GetId() string { return v.Id }

// GetStatus returns GetFullAppApp.Status, and is useful for accessing the field via an interface.
func (v *GetFullAppApp) GetStatus() string { return v.Status }

// GetDeployed returns GetFullAppApp.Deployed, and is useful for accessing the field via an interface.
func (v *GetFullAppApp) GetDeployed() bool { return v.Deployed }

// GetCurrentRelease returns GetFullAppApp.CurrentRelease, and is useful for accessing the field via an interface.
func (v *GetFullAppApp) GetCurrentRelease() GetFullAppAppCurrentRelease { return v.CurrentRelease }

// GetConfig returns GetFullAppApp.Config, and is useful for accessing the field via an interface.
func (v *GetFullAppApp) GetConfig() GetFullAppAppConfig { return v.Config }

// GetHealthChecks returns GetFullAppApp.HealthChecks, and is useful for accessing the field via an interface.
func (v *GetFullAppApp) GetHealthChecks() GetFullAppAppHealthChecksCheckStateConnection {
	return v.HealthChecks
}

// GetIpAddresses returns GetFullAppApp.IpAddresses, and is useful for accessing the field via an interface.
func (v *GetFullAppApp) GetIpAddresses() GetFullAppAppIpAddressesIPAddressConnection {
	return v.IpAddresses
}

// GetRole returns GetFullAppApp.Role, and is useful for accessing the field via an interface.
func (v *GetFullAppApp) GetRole() GetFullAppAppRole { return v.Role }

func (v *GetFullAppApp) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*GetFullAppApp
		Role json.RawMessage `json:"role"`
		graphql.NoUnmarshalJSON
	}
	firstPass.GetFullAppApp = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	{
		dst := &v.Role
		src := firstPass.Role
		if len(src) != 0 && string(src) != "null" {
			err = __unmarshalGetFullAppAppRole(
				src, dst)
			if err != nil {
				return fmt.Errorf(
					"Unable to unmarshal GetFullAppApp.Role: %w", err)
			}
		}
	}
	return nil
}

type __premarshalGetFullAppApp struct {
	Name string `json:"name"`

	Network string `json:"network"`

	Organization GetFullAppAppOrganization `json:"organization"`

	Autoscaling GetFullAppAppAutoscalingAutoscalingConfig `json:"autoscaling"`

	AppUrl string `json:"appUrl"`

	Hostname string `json:"hostname"`

	Id string `json:"id"`

	Status string `json:"status"`

	Deployed bool `json:"deployed"`

	CurrentRelease GetFullAppAppCurrentRelease `json:"currentRelease"`

	Config GetFullAppAppConfig `json:"config"`

	HealthChecks GetFullAppAppHealthChecksCheckStateConnection `json:"healthChecks"`

	IpAddresses GetFullAppAppIpAddressesIPAddressConnection `json:"ipAddresses"`

	Role json.RawMessage `json:"role"`
}

func (v *GetFullAppApp) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *GetFullAppApp) __premarshalJSON() (*__premarshalGetFullAppApp, error) {
	var retval __premarshalGetFullAppApp

	retval.Name = v.Name
	retval.Network = v.Network
	retval.Organization = v.Organization
	retval.Autoscaling = v.Autoscaling
	retval.AppUrl = v.AppUrl
	retval.Hostname = v.Hostname
	retval.Id = v.Id
	retval.Status = v.Status
	retval.Deployed = v.Deployed
	retval.CurrentRelease = v.CurrentRelease
	retval.Config = v.Config
	retval.HealthChecks = v.HealthChecks
	retval.IpAddresses = v.IpAddresses
	{

		dst := &retval.Role
		src := v.Role
		var err error
		*dst, err = __marshalGetFullAppAppRole(
			&src)
		if err != nil {
			return nil, fmt.Errorf(
				"Unable to marshal GetFullAppApp.Role: %w", err)
		}
	}
	return &retval, nil
}

// GetFullAppAppAutoscalingAutoscalingConfig includes the requested fields of the GraphQL type AutoscalingConfig.
type GetFullAppAppAutoscalingAutoscalingConfig struct {
	PreferredRegion string                                                                  `json:"preferredRegion"`
	Regions         []GetFullAppAppAutoscalingAutoscalingConfigRegionsAutoscaleRegionConfig `json:"regions"`
}

// GetPreferredRegion returns GetFullAppAppAutoscalingAutoscalingConfig.PreferredRegion, and is useful for accessing the field via an interface.
func (v *GetFullAppAppAutoscalingAutoscalingConfig) GetPreferredRegion() string {
	return v.PreferredRegion
}

// GetRegions returns GetFullAppAppAutoscalingAutoscalingConfig.Regions, and is useful for accessing the field via an interface.
func (v *GetFullAppAppAutoscalingAutoscalingConfig) GetRegions() []GetFullAppAppAutoscalingAutoscalingConfigRegionsAutoscaleRegionConfig {
	return v.Regions
}

// GetFullAppAppAutoscalingAutoscalingConfigRegionsAutoscaleRegionConfig includes the requested fields of the GraphQL type AutoscaleRegionConfig.
type GetFullAppAppAutoscalingAutoscalingConfigRegionsAutoscaleRegionConfig struct {
	// The region code
	Code string `json:"code"`
}

// GetCode returns GetFullAppAppAutoscalingAutoscalingConfigRegionsAutoscaleRegionConfig.Code, and is useful for accessing the field via an interface.
func (v *GetFullAppAppAutoscalingAutoscalingConfigRegionsAutoscaleRegionConfig) GetCode() string {
	return v.Code
}

// GetFullAppAppConfig includes the requested fields of the GraphQL type AppConfig.
type GetFullAppAppConfig struct {
	Definition interface{} `json:"definition"`
}

// GetDefinition returns GetFullAppAppConfig.Definition, and is useful for accessing the field via an interface.
func (v *GetFullAppAppConfig) GetDefinition() interface{} { return v.Definition }

// GetFullAppAppCurrentRelease includes the requested fields of the GraphQL type Release.
type GetFullAppAppCurrentRelease struct {
	// Unique ID
	Id string `json:"id"`
}

// GetId returns GetFullAppAppCurrentRelease.Id, and is useful for accessing the field via an interface.
func (v *GetFullAppAppCurrentRelease) GetId() string { return v.Id }

// GetFullAppAppHealthChecksCheckStateConnection includes the requested fields of the GraphQL type CheckStateConnection.
// The GraphQL type's documentation follows.
//
// The connection type for CheckState.
type GetFullAppAppHealthChecksCheckStateConnection struct {
	// A list of nodes.
	Nodes []GetFullAppAppHealthChecksCheckStateConnectionNodesCheckState `json:"nodes"`
}

// GetNodes returns GetFullAppAppHealthChecksCheckStateConnection.Nodes, and is useful for accessing the field via an interface.
func (v *GetFullAppAppHealthChecksCheckStateConnection) GetNodes() []GetFullAppAppHealthChecksCheckStateConnectionNodesCheckState {
	return v.Nodes
}

// GetFullAppAppHealthChecksCheckStateConnectionNodesCheckState includes the requested fields of the GraphQL type CheckState.
// The GraphQL type's documentation follows.
//
// health check state
type GetFullAppAppHealthChecksCheckStateConnectionNodesCheckState struct {
	Name   string `json:"name"`
	Status string `json:"status"`
}

// GetName returns GetFullAppAppHealthChecksCheckStateConnectionNodesCheckState.Name, and is useful for accessing the field via an interface.
func (v *GetFullAppAppHealthChecksCheckStateConnectionNodesCheckState) GetName() string {
	return v.Name
}

// GetStatus returns GetFullAppAppHealthChecksCheckStateConnectionNodesCheckState.Status, and is useful for accessing the field via an interface.
func (v *GetFullAppAppHealthChecksCheckStateConnectionNodesCheckState) GetStatus() string {
	return v.Status
}

// GetFullAppAppIpAddressesIPAddressConnection includes the requested fields of the GraphQL type IPAddressConnection.
// The GraphQL type's documentation follows.
//
// The connection type for IPAddress.
type GetFullAppAppIpAddressesIPAddressConnection struct {
	// A list of nodes.
	Nodes []GetFullAppAppIpAddressesIPAddressConnectionNodesIPAddress `json:"nodes"`
}

// GetNodes returns GetFullAppAppIpAddressesIPAddressConnection.Nodes, and is useful for accessing the field via an interface.
func (v *GetFullAppAppIpAddressesIPAddressConnection) GetNodes() []GetFullAppAppIpAddressesIPAddressConnectionNodesIPAddress {
	return v.Nodes
}

// GetFullAppAppIpAddressesIPAddressConnectionNodesIPAddress includes the requested fields of the GraphQL type IPAddress.
type GetFullAppAppIpAddressesIPAddressConnectionNodesIPAddress struct {
	Address string `json:"address"`
	Id      string `json:"id"`
}

// GetAddress returns GetFullAppAppIpAddressesIPAddressConnectionNodesIPAddress.Address, and is useful for accessing the field via an interface.
func (v *GetFullAppAppIpAddressesIPAddressConnectionNodesIPAddress) GetAddress() string {
	return v.Address
}

// GetId returns GetFullAppAppIpAddressesIPAddressConnectionNodesIPAddress.Id, and is useful for accessing the field via an interface.
func (v *GetFullAppAppIpAddressesIPAddressConnectionNodesIPAddress) GetId() string { return v.Id }

// GetFullAppAppOrganization includes the requested fields of the GraphQL type Organization.
type GetFullAppAppOrganization struct {
	Id string `json:"id"`
	// Unique organization slug
	Slug string `json:"slug"`
}

// GetId returns GetFullAppAppOrganization.Id, and is useful for accessing the field via an interface.
func (v *GetFullAppAppOrganization) GetId() string { return v.Id }

// GetSlug returns GetFullAppAppOrganization.Slug, and is useful for accessing the field via an interface.
func (v *GetFullAppAppOrganization) GetSlug() string { return v.Slug }

// GetFullAppAppRole includes the requested fields of the GraphQL interface AppRole.
//
// GetFullAppAppRole is implemented by the following types:
// GetFullAppAppRoleEmptyAppRole
// GetFullAppAppRoleFlyctlMachineHostAppRole
// GetFullAppAppRolePostgresClusterAppRole
// GetFullAppAppRoleRemoteDockerBuilderAppRole
type GetFullAppAppRole interface {
	implementsGraphQLInterfaceGetFullAppAppRole()
	// GetTypename returns the receiver's concrete GraphQL type-name (see interface doc for possible values).
	GetTypename() string
	// GetName returns the interface-field "name" from its implementation.
	// The GraphQL interface field's documentation follows.
	//
	// The name of this role
	GetName() string
}

func (v *GetFullAppAppRoleEmptyAppRole) implementsGraphQLInterfaceGetFullAppAppRole()               {}
func (v *GetFullAppAppRoleFlyctlMachineHostAppRole) implementsGraphQLInterfaceGetFullAppAppRole()   {}
func (v *GetFullAppAppRolePostgresClusterAppRole) implementsGraphQLInterfaceGetFullAppAppRole()     {}
func (v *GetFullAppAppRoleRemoteDockerBuilderAppRole) implementsGraphQLInterfaceGetFullAppAppRole() {}

func __unmarshalGetFullAppAppRole(b []byte, v *GetFullAppAppRole) error {
	if string(b) == "null" {
		return nil
	}

	var tn struct {
		TypeName string `json:"__typename"`
	}
	err := json.Unmarshal(b, &tn)
	if err != nil {
		return err
	}

	switch tn.TypeName {
	case "EmptyAppRole":
		*v = new(GetFullAppAppRoleEmptyAppRole)
		return json.Unmarshal(b, *v)
	case "FlyctlMachineHostAppRole":
		*v = new(GetFullAppAppRoleFlyctlMachineHostAppRole)
		return json.Unmarshal(b, *v)
	case "PostgresClusterAppRole":
		*v = new(GetFullAppAppRolePostgresClusterAppRole)
		return json.Unmarshal(b, *v)
	case "RemoteDockerBuilderAppRole":
		*v = new(GetFullAppAppRoleRemoteDockerBuilderAppRole)
		return json.Unmarshal(b, *v)
	case "":
		return fmt.Errorf(
			"response was missing AppRole.__typename")
	default:
		return fmt.Errorf(
			`unexpected concrete type for GetFullAppAppRole: "%v"`, tn.TypeName)
	}
}

func __marshalGetFullAppAppRole(v *GetFullAppAppRole) ([]byte, error) {

	var typename string
	switch v := (*v).(type) {
	case *GetFullAppAppRoleEmptyAppRole:
		typename = "EmptyAppRole"

		result := struct {
			TypeName string `json:"__typename"`
			*GetFullAppAppRoleEmptyAppRole
		}{typename, v}
		return json.Marshal(result)
	case *GetFullAppAppRoleFlyctlMachineHostAppRole:
		typename = "FlyctlMachineHostAppRole"

		result := struct {
			TypeName string `json:"__typename"`
			*GetFullAppAppRoleFlyctlMachineHostAppRole
		}{typename, v}
		return json.Marshal(result)
	case *GetFullAppAppRolePostgresClusterAppRole:
		typename = "PostgresClusterAppRole"

		result := struct {
			TypeName string `json:"__typename"`
			*GetFullAppAppRolePostgresClusterAppRole
		}{typename, v}
		return json.Marshal(result)
	case *GetFullAppAppRoleRemoteDockerBuilderAppRole:
		typename = "RemoteDockerBuilderAppRole"

		result := struct {
			TypeName string `json:"__typename"`
			*GetFullAppAppRoleRemoteDockerBuilderAppRole
		}{typename, v}
		return json.Marshal(result)
	case nil:
		return []byte("null"), nil
	default:
		return nil, fmt.Errorf(
			`unexpected concrete type for GetFullAppAppRole: "%T"`, v)
	}
}

// GetFullAppAppRoleEmptyAppRole includes the requested fields of the GraphQL type EmptyAppRole.
type GetFullAppAppRoleEmptyAppRole struct {
	Typename string `json:"__typename"`
	// The name of this role
	Name string `json:"name"`
}

// GetTypename returns GetFullAppAppRoleEmptyAppRole.Typename, and is useful for accessing the field via an interface.
func (v *GetFullAppAppRoleEmptyAppRole) GetTypename() string { return v.Typename }

// GetName returns GetFullAppAppRoleEmptyAppRole.Name, and is useful for accessing the field via an interface.
func (v *GetFullAppAppRoleEmptyAppRole) GetName() string { return v.Name }

// GetFullAppAppRoleFlyctlMachineHostAppRole includes the requested fields of the GraphQL type FlyctlMachineHostAppRole.
type GetFullAppAppRoleFlyctlMachineHostAppRole struct {
	Typename string `json:"__typename"`
	// The name of this role
	Name string `json:"name"`
}

// GetTypename returns GetFullAppAppRoleFlyctlMachineHostAppRole.Typename, and is useful for accessing the field via an interface.
func (v *GetFullAppAppRoleFlyctlMachineHostAppRole) GetTypename() string { return v.Typename }

// GetName returns GetFullAppAppRoleFlyctlMachineHostAppRole.Name, and is useful for accessing the field via an interface.
func (v *GetFullAppAppRoleFlyctlMachineHostAppRole) GetName() string { return v.Name }

// GetFullAppAppRolePostgresClusterAppRole includes the requested fields of the GraphQL type PostgresClusterAppRole.
type GetFullAppAppRolePostgresClusterAppRole struct {
	Typename string `json:"__typename"`
	// The name of this role
	Name string `json:"name"`
}

// GetTypename returns GetFullAppAppRolePostgresClusterAppRole.Typename, and is useful for accessing the field via an interface.
func (v *GetFullAppAppRolePostgresClusterAppRole) GetTypename() string { return v.Typename }

// GetName returns GetFullAppAppRolePostgresClusterAppRole.Name, and is useful for accessing the field via an interface.
func (v *GetFullAppAppRolePostgresClusterAppRole) GetName() string { return v.Name }

// GetFullAppAppRoleRemoteDockerBuilderAppRole includes the requested fields of the GraphQL type RemoteDockerBuilderAppRole.
type GetFullAppAppRoleRemoteDockerBuilderAppRole struct {
	Typename string `json:"__typename"`
	// The name of this role
	Name string `json:"name"`
}

// GetTypename returns GetFullAppAppRoleRemoteDockerBuilderAppRole.Typename, and is useful for accessing the field via an interface.
func (v *GetFullAppAppRoleRemoteDockerBuilderAppRole) GetTypename() string { return v.Typename }

// GetName returns GetFullAppAppRoleRemoteDockerBuilderAppRole.Name, and is useful for accessing the field via an interface.
func (v *GetFullAppAppRoleRemoteDockerBuilderAppRole) GetName() string { return v.Name }

// GetFullAppResponse is returned by GetFullApp on success.
type GetFullAppResponse struct {
	// Find an app by name
	App GetFullAppApp `json:"app"`
}

// GetApp returns GetFullAppResponse.App, and is useful for accessing the field via an interface.
func (v *GetFullAppResponse) GetApp() GetFullAppApp { return v.App }

type IPAddressType string

const (
	IPAddressTypeV4 IPAddressType = "v4"
	IPAddressTypeV6 IPAddressType = "v6"
)

// IpAddressQueryApp includes the requested fields of the GraphQL type App.
type IpAddressQueryApp struct {
	// Find an ip address by address string
	IpAddress IpAddressQueryAppIpAddressIPAddress `json:"ipAddress"`
}

// GetIpAddress returns IpAddressQueryApp.IpAddress, and is useful for accessing the field via an interface.
func (v *IpAddressQueryApp) GetIpAddress() IpAddressQueryAppIpAddressIPAddress { return v.IpAddress }

// IpAddressQueryAppIpAddressIPAddress includes the requested fields of the GraphQL type IPAddress.
type IpAddressQueryAppIpAddressIPAddress struct {
	Id      string        `json:"id"`
	Type    IPAddressType `json:"type"`
	Address string        `json:"address"`
	Region  string        `json:"region"`
}

// GetId returns IpAddressQueryAppIpAddressIPAddress.Id, and is useful for accessing the field via an interface.
func (v *IpAddressQueryAppIpAddressIPAddress) GetId() string { return v.Id }

// GetType returns IpAddressQueryAppIpAddressIPAddress.Type, and is useful for accessing the field via an interface.
func (v *IpAddressQueryAppIpAddressIPAddress) GetType() IPAddressType { return v.Type }

// GetAddress returns IpAddressQueryAppIpAddressIPAddress.Address, and is useful for accessing the field via an interface.
func (v *IpAddressQueryAppIpAddressIPAddress) GetAddress() string { return v.Address }

// GetRegion returns IpAddressQueryAppIpAddressIPAddress.Region, and is useful for accessing the field via an interface.
func (v *IpAddressQueryAppIpAddressIPAddress) GetRegion() string { return v.Region }

// IpAddressQueryResponse is returned by IpAddressQuery on success.
type IpAddressQueryResponse struct {
	// Find an app by name
	App IpAddressQueryApp `json:"app"`
}

// GetApp returns IpAddressQueryResponse.App, and is useful for accessing the field via an interface.
func (v *IpAddressQueryResponse) GetApp() IpAddressQueryApp { return v.App }

// OrganizationOrganization includes the requested fields of the GraphQL type Organization.
type OrganizationOrganization struct {
	Id string `json:"id"`
}

// GetId returns OrganizationOrganization.Id, and is useful for accessing the field via an interface.
func (v *OrganizationOrganization) GetId() string { return v.Id }

// OrganizationResponse is returned by Organization on success.
type OrganizationResponse struct {
	// Find an organization by ID
	Organization OrganizationOrganization `json:"organization"`
}

// GetOrganization returns OrganizationResponse.Organization, and is useful for accessing the field via an interface.
func (v *OrganizationResponse) GetOrganization() OrganizationOrganization { return v.Organization }

// OrgsQueryOrganizationsOrganizationConnection includes the requested fields of the GraphQL type OrganizationConnection.
// The GraphQL type's documentation follows.
//
// The connection type for Organization.
type OrgsQueryOrganizationsOrganizationConnection struct {
	// A list of nodes.
	Nodes []OrgsQueryOrganizationsOrganizationConnectionNodesOrganization `json:"nodes"`
}

// GetNodes returns OrgsQueryOrganizationsOrganizationConnection.Nodes, and is useful for accessing the field via an interface.
func (v *OrgsQueryOrganizationsOrganizationConnection) GetNodes() []OrgsQueryOrganizationsOrganizationConnectionNodesOrganization {
	return v.Nodes
}

// OrgsQueryOrganizationsOrganizationConnectionNodesOrganization includes the requested fields of the GraphQL type Organization.
type OrgsQueryOrganizationsOrganizationConnectionNodesOrganization struct {
	// Organization name
	Name string `json:"name"`
	Id   string `json:"id"`
}

// GetName returns OrgsQueryOrganizationsOrganizationConnectionNodesOrganization.Name, and is useful for accessing the field via an interface.
func (v *OrgsQueryOrganizationsOrganizationConnectionNodesOrganization) GetName() string {
	return v.Name
}

// GetId returns OrgsQueryOrganizationsOrganizationConnectionNodesOrganization.Id, and is useful for accessing the field via an interface.
func (v *OrgsQueryOrganizationsOrganizationConnectionNodesOrganization) GetId() string { return v.Id }

// OrgsQueryResponse is returned by OrgsQuery on success.
type OrgsQueryResponse struct {
	Organizations OrgsQueryOrganizationsOrganizationConnection `json:"organizations"`
}

// GetOrganizations returns OrgsQueryResponse.Organizations, and is useful for accessing the field via an interface.
func (v *OrgsQueryResponse) GetOrganizations() OrgsQueryOrganizationsOrganizationConnection {
	return v.Organizations
}

// ReleaseIpAddressReleaseIpAddressReleaseIPAddressPayload includes the requested fields of the GraphQL type ReleaseIPAddressPayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of ReleaseIPAddress
type ReleaseIpAddressReleaseIpAddressReleaseIPAddressPayload struct {
	App ReleaseIpAddressReleaseIpAddressReleaseIPAddressPayloadApp `json:"app"`
}

// GetApp returns ReleaseIpAddressReleaseIpAddressReleaseIPAddressPayload.App, and is useful for accessing the field via an interface.
func (v *ReleaseIpAddressReleaseIpAddressReleaseIPAddressPayload) GetApp() ReleaseIpAddressReleaseIpAddressReleaseIPAddressPayloadApp {
	return v.App
}

// ReleaseIpAddressReleaseIpAddressReleaseIPAddressPayloadApp includes the requested fields of the GraphQL type App.
type ReleaseIpAddressReleaseIpAddressReleaseIPAddressPayloadApp struct {
	// The unique application name
	Name string `json:"name"`
}

// GetName returns ReleaseIpAddressReleaseIpAddressReleaseIPAddressPayloadApp.Name, and is useful for accessing the field via an interface.
func (v *ReleaseIpAddressReleaseIpAddressReleaseIPAddressPayloadApp) GetName() string { return v.Name }

// ReleaseIpAddressResponse is returned by ReleaseIpAddress on success.
type ReleaseIpAddressResponse struct {
	ReleaseIpAddress ReleaseIpAddressReleaseIpAddressReleaseIPAddressPayload `json:"releaseIpAddress"`
}

// GetReleaseIpAddress returns ReleaseIpAddressResponse.ReleaseIpAddress, and is useful for accessing the field via an interface.
func (v *ReleaseIpAddressResponse) GetReleaseIpAddress() ReleaseIpAddressReleaseIpAddressReleaseIPAddressPayload {
	return v.ReleaseIpAddress
}

// Autogenerated input type of RemoveWireGuardPeer
type RemoveWireGuardPeerInput struct {
	// A unique identifier for the client performing the mutation.
	ClientMutationId string `json:"clientMutationId"`
	// The node ID of the organization
	OrganizationId string `json:"organizationId"`
	// The name of the peer to remove
	Name string `json:"name"`
	// Add via NATS transaction (for testing only, nosy users)
	Nats bool `json:"nats"`
}

// GetClientMutationId returns RemoveWireGuardPeerInput.ClientMutationId, and is useful for accessing the field via an interface.
func (v *RemoveWireGuardPeerInput) GetClientMutationId() string { return v.ClientMutationId }

// GetOrganizationId returns RemoveWireGuardPeerInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *RemoveWireGuardPeerInput) GetOrganizationId() string { return v.OrganizationId }

// GetName returns RemoveWireGuardPeerInput.Name, and is useful for accessing the field via an interface.
func (v *RemoveWireGuardPeerInput) GetName() string { return v.Name }

// GetNats returns RemoveWireGuardPeerInput.Nats, and is useful for accessing the field via an interface.
func (v *RemoveWireGuardPeerInput) GetNats() bool { return v.Nats }

// RemoveWireguardPeerRemoveWireGuardPeerRemoveWireGuardPeerPayload includes the requested fields of the GraphQL type RemoveWireGuardPeerPayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of RemoveWireGuardPeer
type RemoveWireguardPeerRemoveWireGuardPeerRemoveWireGuardPeerPayload struct {
	// The organization that owned the peer
	Organization RemoveWireguardPeerRemoveWireGuardPeerRemoveWireGuardPeerPayloadOrganization `json:"organization"`
}

// GetOrganization returns RemoveWireguardPeerRemoveWireGuardPeerRemoveWireGuardPeerPayload.Organization, and is useful for accessing the field via an interface.
func (v *RemoveWireguardPeerRemoveWireGuardPeerRemoveWireGuardPeerPayload) GetOrganization() RemoveWireguardPeerRemoveWireGuardPeerRemoveWireGuardPeerPayloadOrganization {
	return v.Organization
}

// RemoveWireguardPeerRemoveWireGuardPeerRemoveWireGuardPeerPayloadOrganization includes the requested fields of the GraphQL type Organization.
type RemoveWireguardPeerRemoveWireGuardPeerRemoveWireGuardPeerPayloadOrganization struct {
	// Organization name
	Name string `json:"name"`
}

// GetName returns RemoveWireguardPeerRemoveWireGuardPeerRemoveWireGuardPeerPayloadOrganization.Name, and is useful for accessing the field via an interface.
func (v *RemoveWireguardPeerRemoveWireGuardPeerRemoveWireGuardPeerPayloadOrganization) GetName() string {
	return v.Name
}

// RemoveWireguardPeerResponse is returned by RemoveWireguardPeer on success.
type RemoveWireguardPeerResponse struct {
	RemoveWireGuardPeer RemoveWireguardPeerRemoveWireGuardPeerRemoveWireGuardPeerPayload `json:"removeWireGuardPeer"`
}

// GetRemoveWireGuardPeer returns RemoveWireguardPeerResponse.RemoveWireGuardPeer, and is useful for accessing the field via an interface.
func (v *RemoveWireguardPeerResponse) GetRemoveWireGuardPeer() RemoveWireguardPeerRemoveWireGuardPeerRemoveWireGuardPeerPayload {
	return v.RemoveWireGuardPeer
}

// UpdateAutoScaleConfigMutationResponse is returned by UpdateAutoScaleConfigMutation on success.
type UpdateAutoScaleConfigMutationResponse struct {
	UpdateAutoscaleConfig UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayload `json:"updateAutoscaleConfig"`
}

// GetUpdateAutoscaleConfig returns UpdateAutoScaleConfigMutationResponse.UpdateAutoscaleConfig, and is useful for accessing the field via an interface.
func (v *UpdateAutoScaleConfigMutationResponse) GetUpdateAutoscaleConfig() UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayload {
	return v.UpdateAutoscaleConfig
}

// UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayload includes the requested fields of the GraphQL type UpdateAutoscaleConfigPayload.
// The GraphQL type's documentation follows.
//
// Autogenerated return type of UpdateAutoscaleConfig
type UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayload struct {
	App UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadApp `json:"app"`
}

// GetApp returns UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayload.App, and is useful for accessing the field via an interface.
func (v *UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayload) GetApp() UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadApp {
	return v.App
}

// UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadApp includes the requested fields of the GraphQL type App.
type UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadApp struct {
	// Application status
	Status      string                                                                                                        `json:"status"`
	Autoscaling UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadAppAutoscalingAutoscalingConfig `json:"autoscaling"`
}

// GetStatus returns UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadApp.Status, and is useful for accessing the field via an interface.
func (v *UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadApp) GetStatus() string {
	return v.Status
}

// GetAutoscaling returns UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadApp.Autoscaling, and is useful for accessing the field via an interface.
func (v *UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadApp) GetAutoscaling() UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadAppAutoscalingAutoscalingConfig {
	return v.Autoscaling
}

// UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadAppAutoscalingAutoscalingConfig includes the requested fields of the GraphQL type AutoscalingConfig.
type UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadAppAutoscalingAutoscalingConfig struct {
	Regions []UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadAppAutoscalingAutoscalingConfigRegionsAutoscaleRegionConfig `json:"regions"`
}

// GetRegions returns UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadAppAutoscalingAutoscalingConfig.Regions, and is useful for accessing the field via an interface.
func (v *UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadAppAutoscalingAutoscalingConfig) GetRegions() []UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadAppAutoscalingAutoscalingConfigRegionsAutoscaleRegionConfig {
	return v.Regions
}

// UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadAppAutoscalingAutoscalingConfigRegionsAutoscaleRegionConfig includes the requested fields of the GraphQL type AutoscaleRegionConfig.
type UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadAppAutoscalingAutoscalingConfigRegionsAutoscaleRegionConfig struct {
	// The region code
	Code string `json:"code"`
}

// GetCode returns UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadAppAutoscalingAutoscalingConfigRegionsAutoscaleRegionConfig.Code, and is useful for accessing the field via an interface.
func (v *UpdateAutoScaleConfigMutationUpdateAutoscaleConfigUpdateAutoscaleConfigPayloadAppAutoscalingAutoscalingConfigRegionsAutoscaleRegionConfig) GetCode() string {
	return v.Code
}

// VolumeQueryApp includes the requested fields of the GraphQL type App.
type VolumeQueryApp struct {
	Volume VolumeQueryAppVolume `json:"volume"`
}

// GetVolume returns VolumeQueryApp.Volume, and is useful for accessing the field via an interface.
func (v *VolumeQueryApp) GetVolume() VolumeQueryAppVolume { return v.Volume }

// VolumeQueryAppVolume includes the requested fields of the GraphQL type Volume.
type VolumeQueryAppVolume struct {
	Name       string `json:"name"`
	Region     string `json:"region"`
	Id         string `json:"id"`
	InternalId string `json:"internalId"`
	SizeGb     int    `json:"sizeGb"`
}

// GetName returns VolumeQueryAppVolume.Name, and is useful for accessing the field via an interface.
func (v *VolumeQueryAppVolume) GetName() string { return v.Name }

// GetRegion returns VolumeQueryAppVolume.Region, and is useful for accessing the field via an interface.
func (v *VolumeQueryAppVolume) GetRegion() string { return v.Region }

// GetId returns VolumeQueryAppVolume.Id, and is useful for accessing the field via an interface.
func (v *VolumeQueryAppVolume) GetId() string { return v.Id }

// GetInternalId returns VolumeQueryAppVolume.InternalId, and is useful for accessing the field via an interface.
func (v *VolumeQueryAppVolume) GetInternalId() string { return v.InternalId }

// GetSizeGb returns VolumeQueryAppVolume.SizeGb, and is useful for accessing the field via an interface.
func (v *VolumeQueryAppVolume) GetSizeGb() int { return v.SizeGb }

// VolumeQueryResponse is returned by VolumeQuery on success.
type VolumeQueryResponse struct {
	// Find an app by name
	App VolumeQueryApp `json:"app"`
}

// GetApp returns VolumeQueryResponse.App, and is useful for accessing the field via an interface.
func (v *VolumeQueryResponse) GetApp() VolumeQueryApp { return v.App }

// __AddCertificateInput is used internally by genqlient
type __AddCertificateInput struct {
	App      string `json:"app"`
	Hostname string `json:"hostname"`
}

// GetApp returns __AddCertificateInput.App, and is useful for accessing the field via an interface.
func (v *__AddCertificateInput) GetApp() string { return v.App }

// GetHostname returns __AddCertificateInput.Hostname, and is useful for accessing the field via an interface.
func (v *__AddCertificateInput) GetHostname() string { return v.Hostname }

// __AddWireguardPeerInput is used internally by genqlient
type __AddWireguardPeerInput struct {
	Input AddWireGuardPeerInput `json:"input"`
}

// GetInput returns __AddWireguardPeerInput.Input, and is useful for accessing the field via an interface.
func (v *__AddWireguardPeerInput) GetInput() AddWireGuardPeerInput { return v.Input }

// __AllocateIpAddressInput is used internally by genqlient
type __AllocateIpAddressInput struct {
	App      string        `json:"app"`
	Region   string        `json:"region"`
	AddrType IPAddressType `json:"addrType"`
}

// GetApp returns __AllocateIpAddressInput.App, and is useful for accessing the field via an interface.
func (v *__AllocateIpAddressInput) GetApp() string { return v.App }

// GetRegion returns __AllocateIpAddressInput.Region, and is useful for accessing the field via an interface.
func (v *__AllocateIpAddressInput) GetRegion() string { return v.Region }

// GetAddrType returns __AllocateIpAddressInput.AddrType, and is useful for accessing the field via an interface.
func (v *__AllocateIpAddressInput) GetAddrType() IPAddressType { return v.AddrType }

// __CreateAppMutationInput is used internally by genqlient
type __CreateAppMutationInput struct {
	Name           string `json:"name"`
	OrganizationId string `json:"organizationId"`
}

// GetName returns __CreateAppMutationInput.Name, and is useful for accessing the field via an interface.
func (v *__CreateAppMutationInput) GetName() string { return v.Name }

// GetOrganizationId returns __CreateAppMutationInput.OrganizationId, and is useful for accessing the field via an interface.
func (v *__CreateAppMutationInput) GetOrganizationId() string { return v.OrganizationId }

// __CreatePostgresClusterInput is used internally by genqlient
type __CreatePostgresClusterInput struct {
	Name       string `json:"name"`
	Orgid      string `json:"orgid"`
	Region     string `json:"region"`
	Password   string `json:"password"`
	Vmsize     string `json:"vmsize"`
	Volumesize int    `json:"volumesize"`
	Count      int    `json:"count"`
	Imageref   string `json:"imageref"`
}

// GetName returns __CreatePostgresClusterInput.Name, and is useful for accessing the field via an interface.
func (v *__CreatePostgresClusterInput) GetName() string { return v.Name }

// GetOrgid returns __CreatePostgresClusterInput.Orgid, and is useful for accessing the field via an interface.
func (v *__CreatePostgresClusterInput) GetOrgid() string { return v.Orgid }

// GetRegion returns __CreatePostgresClusterInput.Region, and is useful for accessing the field via an interface.
func (v *__CreatePostgresClusterInput) GetRegion() string { return v.Region }

// GetPassword returns __CreatePostgresClusterInput.Password, and is useful for accessing the field via an interface.
func (v *__CreatePostgresClusterInput) GetPassword() string { return v.Password }

// GetVmsize returns __CreatePostgresClusterInput.Vmsize, and is useful for accessing the field via an interface.
func (v *__CreatePostgresClusterInput) GetVmsize() string { return v.Vmsize }

// GetVolumesize returns __CreatePostgresClusterInput.Volumesize, and is useful for accessing the field via an interface.
func (v *__CreatePostgresClusterInput) GetVolumesize() int { return v.Volumesize }

// GetCount returns __CreatePostgresClusterInput.Count, and is useful for accessing the field via an interface.
func (v *__CreatePostgresClusterInput) GetCount() int { return v.Count }

// GetImageref returns __CreatePostgresClusterInput.Imageref, and is useful for accessing the field via an interface.
func (v *__CreatePostgresClusterInput) GetImageref() string { return v.Imageref }

// __CreateVolumeInput is used internally by genqlient
type __CreateVolumeInput struct {
	App    string `json:"app"`
	Name   string `json:"name"`
	Region string `json:"region"`
	SizeGb int    `json:"sizeGb"`
}

// GetApp returns __CreateVolumeInput.App, and is useful for accessing the field via an interface.
func (v *__CreateVolumeInput) GetApp() string { return v.App }

// GetName returns __CreateVolumeInput.Name, and is useful for accessing the field via an interface.
func (v *__CreateVolumeInput) GetName() string { return v.Name }

// GetRegion returns __CreateVolumeInput.Region, and is useful for accessing the field via an interface.
func (v *__CreateVolumeInput) GetRegion() string { return v.Region }

// GetSizeGb returns __CreateVolumeInput.SizeGb, and is useful for accessing the field via an interface.
func (v *__CreateVolumeInput) GetSizeGb() int { return v.SizeGb }

// __DeleteAppMutationInput is used internally by genqlient
type __DeleteAppMutationInput struct {
	Name string `json:"name"`
}

// GetName returns __DeleteAppMutationInput.Name, and is useful for accessing the field via an interface.
func (v *__DeleteAppMutationInput) GetName() string { return v.Name }

// __DeleteCertificateInput is used internally by genqlient
type __DeleteCertificateInput struct {
	App      string `json:"app"`
	Hostname string `json:"hostname"`
}

// GetApp returns __DeleteCertificateInput.App, and is useful for accessing the field via an interface.
func (v *__DeleteCertificateInput) GetApp() string { return v.App }

// GetHostname returns __DeleteCertificateInput.Hostname, and is useful for accessing the field via an interface.
func (v *__DeleteCertificateInput) GetHostname() string { return v.Hostname }

// __DeleteVolumeInput is used internally by genqlient
type __DeleteVolumeInput struct {
	Volume string `json:"volume"`
}

// GetVolume returns __DeleteVolumeInput.Volume, and is useful for accessing the field via an interface.
func (v *__DeleteVolumeInput) GetVolume() string { return v.Volume }

// __GetCertificateInput is used internally by genqlient
type __GetCertificateInput struct {
	App      string `json:"app"`
	Hostname string `json:"hostname"`
}

// GetApp returns __GetCertificateInput.App, and is useful for accessing the field via an interface.
func (v *__GetCertificateInput) GetApp() string { return v.App }

// GetHostname returns __GetCertificateInput.Hostname, and is useful for accessing the field via an interface.
func (v *__GetCertificateInput) GetHostname() string { return v.Hostname }

// __GetFullAppInput is used internally by genqlient
type __GetFullAppInput struct {
	Name string `json:"name"`
}

// GetName returns __GetFullAppInput.Name, and is useful for accessing the field via an interface.
func (v *__GetFullAppInput) GetName() string { return v.Name }

// __IpAddressQueryInput is used internally by genqlient
type __IpAddressQueryInput struct {
	App  string `json:"app"`
	Addr string `json:"addr"`
}

// GetApp returns __IpAddressQueryInput.App, and is useful for accessing the field via an interface.
func (v *__IpAddressQueryInput) GetApp() string { return v.App }

// GetAddr returns __IpAddressQueryInput.Addr, and is useful for accessing the field via an interface.
func (v *__IpAddressQueryInput) GetAddr() string { return v.Addr }

// __OrganizationInput is used internally by genqlient
type __OrganizationInput struct {
	Slug string `json:"slug"`
}

// GetSlug returns __OrganizationInput.Slug, and is useful for accessing the field via an interface.
func (v *__OrganizationInput) GetSlug() string { return v.Slug }

// __ReleaseIpAddressInput is used internally by genqlient
type __ReleaseIpAddressInput struct {
	AddressId string `json:"addressId"`
}

// GetAddressId returns __ReleaseIpAddressInput.AddressId, and is useful for accessing the field via an interface.
func (v *__ReleaseIpAddressInput) GetAddressId() string { return v.AddressId }

// __RemoveWireguardPeerInput is used internally by genqlient
type __RemoveWireguardPeerInput struct {
	Input RemoveWireGuardPeerInput `json:"input"`
}

// GetInput returns __RemoveWireguardPeerInput.Input, and is useful for accessing the field via an interface.
func (v *__RemoveWireguardPeerInput) GetInput() RemoveWireGuardPeerInput { return v.Input }

// __UpdateAutoScaleConfigMutationInput is used internally by genqlient
type __UpdateAutoScaleConfigMutationInput struct {
	Id           string                       `json:"id"`
	Regions      []AutoscaleRegionConfigInput `json:"regions"`
	ResetRegions bool                         `json:"resetRegions"`
}

// GetId returns __UpdateAutoScaleConfigMutationInput.Id, and is useful for accessing the field via an interface.
func (v *__UpdateAutoScaleConfigMutationInput) GetId() string { return v.Id }

// GetRegions returns __UpdateAutoScaleConfigMutationInput.Regions, and is useful for accessing the field via an interface.
func (v *__UpdateAutoScaleConfigMutationInput) GetRegions() []AutoscaleRegionConfigInput {
	return v.Regions
}

// GetResetRegions returns __UpdateAutoScaleConfigMutationInput.ResetRegions, and is useful for accessing the field via an interface.
func (v *__UpdateAutoScaleConfigMutationInput) GetResetRegions() bool { return v.ResetRegions }

// __VolumeQueryInput is used internally by genqlient
type __VolumeQueryInput struct {
	App      string `json:"app"`
	Internal string `json:"internal"`
}

// GetApp returns __VolumeQueryInput.App, and is useful for accessing the field via an interface.
func (v *__VolumeQueryInput) GetApp() string { return v.App }

// GetInternal returns __VolumeQueryInput.Internal, and is useful for accessing the field via an interface.
func (v *__VolumeQueryInput) GetInternal() string { return v.Internal }

func AddCertificate(
	ctx context.Context,
	client graphql.Client,
	app string,
	hostname string,
) (*AddCertificateResponse, error) {
	__input := __AddCertificateInput{
		App:      app,
		Hostname: hostname,
	}
	var err error

	var retval AddCertificateResponse
	err = client.MakeRequest(
		ctx,
		"AddCertificate",
		`
mutation AddCertificate ($app: ID!, $hostname: String!) {
	addCertificate(appId: $app, hostname: $hostname) {
		certificate {
			id
			dnsValidationInstructions
			dnsValidationHostname
			dnsValidationTarget
			hostname
			check
		}
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

func AddWireguardPeer(
	ctx context.Context,
	client graphql.Client,
	input AddWireGuardPeerInput,
) (*AddWireguardPeerResponse, error) {
	__input := __AddWireguardPeerInput{
		Input: input,
	}
	var err error

	var retval AddWireguardPeerResponse
	err = client.MakeRequest(
		ctx,
		"AddWireguardPeer",
		`
mutation AddWireguardPeer ($input: AddWireGuardPeerInput!) {
	addWireGuardPeer(input: $input) {
		network
		endpointip
		peerip
		pubkey
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

func AllocateIpAddress(
	ctx context.Context,
	client graphql.Client,
	app string,
	region string,
	addrType IPAddressType,
) (*AllocateIpAddressResponse, error) {
	__input := __AllocateIpAddressInput{
		App:      app,
		Region:   region,
		AddrType: addrType,
	}
	var err error

	var retval AllocateIpAddressResponse
	err = client.MakeRequest(
		ctx,
		"AllocateIpAddress",
		`
mutation AllocateIpAddress ($app: ID!, $region: String, $addrType: IPAddressType) {
	allocateIpAddress(input: {appId:$app,region:$region,type:$addrType}) {
		ipAddress {
			id
			type
			address
			region
		}
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

func CreateAppMutation(
	ctx context.Context,
	client graphql.Client,
	name string,
	organizationId string,
) (*CreateAppMutationResponse, error) {
	__input := __CreateAppMutationInput{
		Name:           name,
		OrganizationId: organizationId,
	}
	var err error

	var retval CreateAppMutationResponse
	err = client.MakeRequest(
		ctx,
		"CreateAppMutation",
		`
mutation CreateAppMutation ($name: String, $organizationId: ID!) {
	createApp(input: {name:$name,organizationId:$organizationId}) {
		app {
			name
			status
			organization {
				id
				slug
			}
		}
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

func CreatePostgresCluster(
	ctx context.Context,
	client graphql.Client,
	name string,
	orgid string,
	region string,
	password string,
	vmsize string,
	volumesize int,
	count int,
	imageref string,
) (*CreatePostgresClusterResponse, error) {
	__input := __CreatePostgresClusterInput{
		Name:       name,
		Orgid:      orgid,
		Region:     region,
		Password:   password,
		Vmsize:     vmsize,
		Volumesize: volumesize,
		Count:      count,
		Imageref:   imageref,
	}
	var err error

	var retval CreatePostgresClusterResponse
	err = client.MakeRequest(
		ctx,
		"CreatePostgresCluster",
		`
mutation CreatePostgresCluster ($name: String, $orgid: ID!, $region: String, $password: String, $vmsize: String, $volumesize: Int, $count: Int, $imageref: String) {
	createPostgresCluster(input: {name:$name,organizationId:$orgid,region:$region,password:$password,vmSize:$vmsize,volumeSizeGb:$volumesize,count:$count,imageRef:$imageref}) {
		app {
			name
		}
		username
		password
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

func CreateVolume(
	ctx context.Context,
	client graphql.Client,
	app string,
	name string,
	region string,
	sizeGb int,
) (*CreateVolumeResponse, error) {
	__input := __CreateVolumeInput{
		App:    app,
		Name:   name,
		Region: region,
		SizeGb: sizeGb,
	}
	var err error

	var retval CreateVolumeResponse
	err = client.MakeRequest(
		ctx,
		"CreateVolume",
		`
mutation CreateVolume ($app: ID!, $name: String!, $region: String!, $sizeGb: Int!) {
	createVolume(input: {appId:$app,name:$name,region:$region,sizeGb:$sizeGb}) {
		volume {
			name
			region
			id
			internalId
			region
			sizeGb
		}
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

func DeleteAppMutation(
	ctx context.Context,
	client graphql.Client,
	name string,
) (*DeleteAppMutationResponse, error) {
	__input := __DeleteAppMutationInput{
		Name: name,
	}
	var err error

	var retval DeleteAppMutationResponse
	err = client.MakeRequest(
		ctx,
		"DeleteAppMutation",
		`
mutation DeleteAppMutation ($name: ID!) {
	deleteApp(appId: $name) {
		organization {
			name
		}
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

func DeleteCertificate(
	ctx context.Context,
	client graphql.Client,
	app string,
	hostname string,
) (*DeleteCertificateResponse, error) {
	__input := __DeleteCertificateInput{
		App:      app,
		Hostname: hostname,
	}
	var err error

	var retval DeleteCertificateResponse
	err = client.MakeRequest(
		ctx,
		"DeleteCertificate",
		`
mutation DeleteCertificate ($app: ID!, $hostname: String!) {
	deleteCertificate(appId: $app, hostname: $hostname) {
		app {
			name
		}
		certificate {
			hostname
			id
		}
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

func DeleteVolume(
	ctx context.Context,
	client graphql.Client,
	volume string,
) (*DeleteVolumeResponse, error) {
	__input := __DeleteVolumeInput{
		Volume: volume,
	}
	var err error

	var retval DeleteVolumeResponse
	err = client.MakeRequest(
		ctx,
		"DeleteVolume",
		`
mutation DeleteVolume ($volume: ID!) {
	deleteVolume(input: {volumeId:$volume}) {
		clientMutationId
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

func GetCertificate(
	ctx context.Context,
	client graphql.Client,
	app string,
	hostname string,
) (*GetCertificateResponse, error) {
	__input := __GetCertificateInput{
		App:      app,
		Hostname: hostname,
	}
	var err error

	var retval GetCertificateResponse
	err = client.MakeRequest(
		ctx,
		"GetCertificate",
		`
query GetCertificate ($app: String!, $hostname: String!) {
	app(name: $app) {
		certificate(hostname: $hostname) {
			id
			dnsValidationInstructions
			dnsValidationHostname
			dnsValidationTarget
			hostname
			check
		}
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

func GetFullApp(
	ctx context.Context,
	client graphql.Client,
	name string,
) (*GetFullAppResponse, error) {
	__input := __GetFullAppInput{
		Name: name,
	}
	var err error

	var retval GetFullAppResponse
	err = client.MakeRequest(
		ctx,
		"GetFullApp",
		`
query GetFullApp ($name: String) {
	app(name: $name) {
		name
		network
		organization {
			id
			slug
		}
		autoscaling {
			preferredRegion
			regions {
				code
			}
		}
		appUrl
		hostname
		id
		status
		deployed
		currentRelease {
			id
		}
		config {
			definition
		}
		healthChecks {
			nodes {
				name
				status
			}
		}
		ipAddresses {
			nodes {
				address
				id
			}
		}
		role {
			__typename
			name
		}
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

func IpAddressQuery(
	ctx context.Context,
	client graphql.Client,
	app string,
	addr string,
) (*IpAddressQueryResponse, error) {
	__input := __IpAddressQueryInput{
		App:  app,
		Addr: addr,
	}
	var err error

	var retval IpAddressQueryResponse
	err = client.MakeRequest(
		ctx,
		"IpAddressQuery",
		`
query IpAddressQuery ($app: String, $addr: String!) {
	app(name: $app) {
		ipAddress(address: $addr) {
			id
			type
			address
			region
		}
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

func Organization(
	ctx context.Context,
	client graphql.Client,
	slug string,
) (*OrganizationResponse, error) {
	__input := __OrganizationInput{
		Slug: slug,
	}
	var err error

	var retval OrganizationResponse
	err = client.MakeRequest(
		ctx,
		"Organization",
		`
query Organization ($slug: String) {
	organization(slug: $slug) {
		id
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

func OrgsQuery(
	ctx context.Context,
	client graphql.Client,
) (*OrgsQueryResponse, error) {
	var err error

	var retval OrgsQueryResponse
	err = client.MakeRequest(
		ctx,
		"OrgsQuery",
		`
query OrgsQuery {
	organizations {
		nodes {
			name
			id
		}
	}
}
`,
		&retval,
		nil,
	)
	return &retval, err
}

func ReleaseIpAddress(
	ctx context.Context,
	client graphql.Client,
	addressId string,
) (*ReleaseIpAddressResponse, error) {
	__input := __ReleaseIpAddressInput{
		AddressId: addressId,
	}
	var err error

	var retval ReleaseIpAddressResponse
	err = client.MakeRequest(
		ctx,
		"ReleaseIpAddress",
		`
mutation ReleaseIpAddress ($addressId: ID!) {
	releaseIpAddress(input: {ipAddressId:$addressId}) {
		app {
			name
		}
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

func RemoveWireguardPeer(
	ctx context.Context,
	client graphql.Client,
	input RemoveWireGuardPeerInput,
) (*RemoveWireguardPeerResponse, error) {
	__input := __RemoveWireguardPeerInput{
		Input: input,
	}
	var err error

	var retval RemoveWireguardPeerResponse
	err = client.MakeRequest(
		ctx,
		"RemoveWireguardPeer",
		`
mutation RemoveWireguardPeer ($input: RemoveWireGuardPeerInput!) {
	removeWireGuardPeer(input: $input) {
		organization {
			name
		}
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

func UpdateAutoScaleConfigMutation(
	ctx context.Context,
	client graphql.Client,
	id string,
	regions []AutoscaleRegionConfigInput,
	resetRegions bool,
) (*UpdateAutoScaleConfigMutationResponse, error) {
	__input := __UpdateAutoScaleConfigMutationInput{
		Id:           id,
		Regions:      regions,
		ResetRegions: resetRegions,
	}
	var err error

	var retval UpdateAutoScaleConfigMutationResponse
	err = client.MakeRequest(
		ctx,
		"UpdateAutoScaleConfigMutation",
		`
mutation UpdateAutoScaleConfigMutation ($id: ID!, $regions: [AutoscaleRegionConfigInput!], $resetRegions: Boolean) {
	updateAutoscaleConfig(input: {resetRegions:$resetRegions,regions:$regions,appId:$id}) {
		app {
			status
			autoscaling {
				regions {
					code
				}
			}
		}
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}

func VolumeQuery(
	ctx context.Context,
	client graphql.Client,
	app string,
	internal string,
) (*VolumeQueryResponse, error) {
	__input := __VolumeQueryInput{
		App:      app,
		Internal: internal,
	}
	var err error

	var retval VolumeQueryResponse
	err = client.MakeRequest(
		ctx,
		"VolumeQuery",
		`
query VolumeQuery ($app: String, $internal: String!) {
	app(name: $app) {
		volume(internalId: $internal) {
			name
			region
			id
			internalId
			region
			sizeGb
		}
	}
}
`,
		&retval,
		&__input,
	)
	return &retval, err
}
